version: '3'
services:
  dblocal: 
    image: 'redis'
    container_name: dblocal
    volumes:
      - dblocal-data:/bitnami/redis/data
    build: 
      context: ./..
      dockerfile: docker/dockerfile-dblocal
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        interval: 2s
        timeout: 2s
        retries: 10
      
  broker:
    image: eclipse-mosquitto:2
    container_name: broker
    tty: true
    volumes:
      - ./../broker/config/:/mosquitto/config/:ro
      - ./../broker/log/:/mosquitto/log/
      - broker-data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  
  pulsor:
    build: 
      context: ./..
      dockerfile: docker/dockerfile-pulsor
    container_name: pulsor
    ports:
      - "7071:7071"
    depends_on:
      dblocal:
        condition: service_healthy
    volumes:
      - pulsor-data:/usr/app/
      - pulsor-data:/usr/app/node_modules
  
  dbcloud:
    tty: true
    image: mysql:5.7
    container_name: dbcloud
    build: 
      context: ./..
      dockerfile: docker/dockerfile-dbcloud
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 2s
        timeout: 2s
        retries: 10
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'AirLuxDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - dbcloud-data:/var/lib/mysql
  
  syncapi:
    tty: true
    image: bitnami/laravel
    container_name: syncapi
    build: 
      context: ./..
      dockerfile: docker/dockerfile-syncapp
    working_dir: /var/www/
    ports:
      - "80:80"
    extra_hosts:
        host.docker.internal: host-gateway
    depends_on:
      dbcloud:
        condition: service_healthy
    healthcheck:
        test: "curl -f http://syncapi/api/captor/:80"
        interval: 2s
        timeout: 2s
        retries: 10
    environment:
      MYSQL_HOST: 'dbcloud'
      MYSQL_DATABASE: 'AirLuxDB'
    volumes:
      - syncapp-data:/var/www

  dbstats:
    image: quay.io/prometheus/prometheus:latest
    container_name: dbstats
    volumes:
      - ./../dbstats:/etc/prometheus
      - dbstats_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '-storage.local.path=/prometheus'
    ports:
      - 9090:9090
    links:
      - mysqld-exporter
      
  statsapp:
    image: grafana/grafana:latest
    container_name: statsapp
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_ALERTING_EXECUTE_ALERTS=false
    volumes:
      - statsapp_data:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - dbstats
    depends_on:
      - dbstats
      
  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    command:
     - --collect.info_schema.tablestats
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root@(dbcloud:3306)/
    ports:
      - 9104:9104
    links:
      - dbcloud
    depends_on:
      dbcloud:
        condition: service_healthy
  
      
# Names our volume
volumes:
  dbcloud-data:
  dblocal-data:
  syncapp-data:
  pulsor-data:
  broker-data:
  dbstats_data: {}
  statsapp_data: {}
      