version: '3'
services:
  dblocal: 
    image: 'redis'
    container_name: dblocal
    tty: true
    volumes:
      - ./dblocal:/usr/local/etc/redis
      - dblocal-data:/bitnami/redis/data
    ports:
      - 6379:6379
    build: 
      context: ./..
      dockerfile: docker/dockerfile-dblocal
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        interval: 2s
        timeout: 2s
        retries: 10
    networks:
      - iotnetwork


  localapp:
    image: 'localapp'
    container_name: localapp
    tty: true
    build: 
      context: ./..
      dockerfile: docker/dockerfile-localapp
    environment:
      CLIENT_ID: 'Air_Lux_Test'
    depends_on:
      - broker
      - syncapi
      - dblocal
    #command: bash -c "node index.js"
    volumes:
      - ./../localapp/:/usr/app/
      - localapp-data:/usr/app/
      - localapp-data:/usr/app/node_modules
    networks:
      - iotnetwork


  broker:
    image: eclipse-mosquitto:2
    container_name: broker
    tty: true
    volumes:
      - ./../broker/config/:/mosquitto/config/:ro
      - ./../broker/log/:/mosquitto/log/
      - broker-data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - iotnetwork

  
  pulsor1:
    build: 
      context: ./..
      dockerfile: docker/dockerfile-pulsor
    container_name: pulsor1
    environment:
      PULSOR_ID: '0000001'
    depends_on:
      dblocal:
        condition: service_healthy
    volumes:
      - pulsor1-data:/usr/app/
      - pulsor1-data:/usr/app/node_modules
    networks:
      - iotnetwork
  
  pulsor2:
    build: 
      context: ./..
      dockerfile: docker/dockerfile-pulsor
    container_name: pulsor2
    environment:
      PULSOR_ID: '0000002'
    depends_on:
      dblocal:
        condition: service_healthy
    volumes:
      - pulsor2-data:/usr/app/
      - pulsor2-data:/usr/app/node_modules
    networks:
      - iotnetwork
      

  
  pulsor3:
    build: 
      context: ./..
      dockerfile: docker/dockerfile-pulsor
    container_name: pulsor3
    environment:
      PULSOR_ID: '0000003'
    depends_on:
      dblocal:
        condition: service_healthy
    volumes:
      - pulsor3-data:/usr/app/
      - pulsor3-data:/usr/app/node_modules
    networks:
      - iotnetwork

  
  actuator:
    build: 
      context: ./..
      dockerfile: docker/dockerfile-actuator
    container_name: actuator
    environment:
      ACTUATOR_ID: '0000003'
    depends_on:
      dblocal:
        condition: service_healthy
    volumes:
      - actuator-data:/usr/app/
      - actuator-data:/usr/app/node_modules
    networks:
      - iotnetwork

  
  dbcloud:
    tty: true
    image: mysql:5.7
    container_name: dbcloud
    build: 
      context: ./..
      dockerfile: docker/dockerfile-dbcloud
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 3s
        timeout: 4s
        retries: 10
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'AirLuxDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - dbcloud-data:/var/lib/mysql
    networks:
      - iotnetwork
  
  syncapi:
    tty: true
    container_name: syncapi
    build: 
      context: ./..
      dockerfile: docker/dockerfile-syncapp
    ports:
#      - "80:80"
      - "6001:6001"
    extra_hosts:
        host.docker.internal: host-gateway
    depends_on:
      - dbcloud
    environment:
      MYSQL_HOST: 'dbcloud'
      MYSQL_DATABASE: 'AirLuxDB'
    volumes:
      - ./../syncapi/:/usr/app/
      - syncapi-data:/usr/app/
      - syncapi-data:/usr/app/node_modules
    networks:
      - iotnetwork

  dbstats:
    image: quay.io/prometheus/prometheus:latest
    container_name: dbstats
    volumes:
      - ./../dbstats:/etc/prometheus
      - dbstats_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '-storage.local.path=/prometheus'
    ports:
      - 9090:9090
    links:
      - mysqld-exporter
    networks:
      - iotnetwork
      
  statsapp:
    image: grafana/grafana:latest
    container_name: statsapp
    environment:
      - GRAFANA_MYSQL_PASSWORD=password
      - GF_SECURITY_ADMIN_PASSWORD=secret
      - GF_ALERTING_EXECUTE_ALERTS=false
    volumes:
      - ./../statsapp/datasources/:/usr/share/grafana/conf/provisioning/datasources/
      - statsapp_data:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - dbstats
    depends_on:
      - dbstats
    networks:
      - iotnetwork
      
  mysqld-exporter:
    image: quay.io/prometheus/mysqld-exporter
    command:
     - --collect.info_schema.tablestats
    container_name: mysqld-exporter
    environment:
      - DATA_SOURCE_NAME=root:password@(dbcloud:3306)/
    ports:
      - 9104:9104
    links:
      - dbcloud
    depends_on:
      - dbcloud
    networks:
      - iotnetwork
      
networks:
  iotnetwork:
      
      
# Names our volume
volumes:
  dbcloud-data:
  dblocal-data:
  syncapi-data:
  broker-data:
  localapp-data:
  actuator-data:
  pulsor1-data:
  pulsor2-data:
  pulsor3-data:
  dbstats_data: {}
  statsapp_data: {}
      
