version: '3'
services:
  dblocal: 
    image: 'redis'
    container_name: dblocal
    volumes:
      - dblocal-data:/bitnami/redis/data
    build: 
      context: ./..
      dockerfile: docker/dockerfile-dblocal
    healthcheck:
        test: ["CMD", "redis-cli","ping"]
        interval: 2s
        timeout: 2s
        retries: 10
  localapp:
    image: 'localapp'
    container_name: localapp
    build: 
      context: ./..
      dockerfile: docker/dockerfile-localapp
    command: bash -c "node index.js"
    volumes:
      - .:/localapp
    ports:
      - "8080:8080"
    depends_on:
      - syncapi
  broker:
    image: eclipse-mosquitto:2
    container_name: broker
    tty: true
    volumes:
      - ./../broker/config/:/mosquitto/config/:ro
      - ./../broker/log/:/mosquitto/log/
      - broker-data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  
  pulsor:
    build: 
      context: ./..
      dockerfile: docker/dockerfile-pulsor
    container_name: pulsor
    ports:
      - "7071:7071"
    depends_on:
      dblocal:
        condition: service_healthy
    volumes:
      - pulsor-data:/usr/app/
      - pulsor-data:/usr/app/node_modules
  
  dbcloud:
    tty: true
    image: mysql:5.7
    container_name: dbcloud
    build: 
      context: ./..
      dockerfile: docker/dockerfile-dbcloud
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 2s
        timeout: 2s
        retries: 10
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'AirLuxDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - dbcloud-data:/var/lib/mysql
  
  syncapi:
    tty: true
    image: bitnami/laravel
    container_name: syncapi
    build: 
      context: ./..
      dockerfile: docker/dockerfile-syncapp
    working_dir: /var/www/
    ports:
      - "80:80"
    extra_hosts:
        host.docker.internal: host-gateway
    depends_on:
      dbcloud:
        condition: service_healthy
    healthcheck:
        test: "curl -f http://syncapi/api/captor/:80"
        interval: 2s
        timeout: 2s
        retries: 10
    environment:
      MYSQL_HOST: 'dbcloud'
      MYSQL_DATABASE: 'AirLuxDB'
    volumes:
      - syncapp-data:/var/www
      
# Names our volume
volumes:
  dbcloud-data:
  dblocal-data:
  syncapp-data:
  pulsor-data:
  broker-data:
      