---
name: Arduino_CI

on: 
  push:
    branches: [ "temperature" ]

jobs:
  arduino_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: Arduino-CI/action@stable-1.x
        with:
          path: './Temperature/sketch_feb10a'