---
name: Arduino CI
on: 
  push:
    branches: [ "temperature" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Arduino IDE
      uses: hay-kot/arduino-ide-action@v1.0
    - name: Install library dependencies
      run: |
        arduino-cli lib install "ArduinoUnit"
    - name: Compile code and run tests
      run: |
        arduino-cli compile --fqbn arduino:avr:uno .
        arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:uno .
        arduino-cli serial monitor -p /dev/ttyACM0 --baud 9600
        arduino-cli board details --fqbn arduino:avr:uno